import pytest
from fastapi.testclient import TestClient
from unittest.mock import patch, MagicMock, AsyncMock
from datetime import datetime, timezone, timedelta

from app.main import app
from app.dependencies import get_current_user

client = TestClient(app)


# Override authentication dependency for tests
def override_get_current_user():
    return {"uid": "mock_passenger_123", "email": "test@passenger.com"}

app.dependency_overrides[get_current_user] = override_get_current_user

@patch("app.routers.trips.firestore.client")
@patch("app.routers.trips.estimate_tolls_for_route", new_callable=AsyncMock)
def test_calculate_fare_success(mock_estimate_tolls, mock_firestore_client):
    # 1. Mock the AI toll estimation to return a predictable value
    mock_estimate_tolls.return_value = 45.50

    # 2. Mock Firestore to return a valid route
    mock_db = MagicMock()
    mock_firestore_client.return_value = mock_db
    mock_route_doc = MagicMock()
    mock_route_doc.exists = True
    mock_route_doc.to_dict.return_value = {
        "base_distance_km": 100.0,
        "point_a_start": "Pretoria",
        "point_b_end": "Johannesburg"
    }
    mock_db.collection.return_value.document.return_value.get.return_value = mock_route_doc

    # Payload matching the FareCalculationRequest schema
    payload = {
        "route_id": "valid_route_id",
        "trip_time": datetime.now(timezone.utc).isoformat(),
        "passengers_count": 2,
        "tolls_estimated": 0.0 # Will be overwritten by the backend's AI call
    }

    response = client.post("/api/v1/trips/calculate-fare", json=payload)

    # 3. Assertions
    assert response.status_code == 200
    data = response.json()
    assert "base_fare" in data
    assert "total_cost" in data
    assert data["tolls"] == 45.50
    assert data["strategy_applied"] in ["Standard", "Peak Hour (+25%)"]

@patch("app.routers.trips.firestore.client")
def test_calculate_fare_route_not_found(mock_firestore_client):
    # Mock Firestore to return a non-existent route
    mock_db = MagicMock()
    mock_firestore_client.return_value = mock_db
    mock_route_doc = MagicMock()
    mock_route_doc.exists = False
    mock_db.collection.return_value.document.return_value.get.return_value = mock_route_doc

    payload = {
        "route_id": "invalid_route_id",
        "trip_time": datetime.now(timezone.utc).isoformat(),
        "passengers_count": 1,
        "tolls_estimated": 0.0
    }

    response = client.post("/api/v1/trips/calculate-fare", json=payload)

    assert response.status_code == 404
    assert response.json()["detail"] == "Route not found"

@patch("app.routers.trips.firestore.client")
def test_book_trip_success(mock_firestore_client):
    # Mock Firestore setup
    mock_db = MagicMock()
    mock_firestore_client.return_value = mock_db
    mock_document = MagicMock()
    mock_db.collection.return_value.document.return_value = mock_document

    # Payload matching the TripCreate schema
    payload = {
        "route_id": "test_route_123",
        "driver_id": "test_driver_456",
        "departure_time": (datetime.now(timezone.utc) + timedelta(days=1)).isoformat(),
        "status": "Pending"
    }

    response = client.post("/api/v1/trips/book", json=payload)

    # Assertions
    assert response.status_code == 200
    data = response.json()
    assert data["passenger_id"] == "mock_passenger_123" # Injected by dependency
    assert "id" in data # UUID generated by backend
    assert data["status"] == "Pending"
    
    # Verify the document was saved
    mock_document.set.assert_called_once()